### ISSUE TITLE
"Correcting USB Power" ambiguity with "STA Edge Case"

### ISSUE THREAD

**Issue by ChasonDeshotel** [dortania/Getting-Started-With-ACPI#10]
The guide says under "STA Edge Case" (emphasis mine)

>Do note that if your PNP0C09 device has a Method (_STA already you can skip down to "What happens if no PNP0C09 show up?". The reason for this is that **the real EC is considered disabled** already.

but in the next section for "Correcting USB Power"

>Note that it requires the EC functioning correctly

Can I not correct USB power since my EC is natively disabled? Or would "it requires the EC functioning correctly or an STA edge case chip" be accurate?

And out of curiosity, what does "considered" disabled mean?

edit: Great guide so far, btw. Kudos

**Comment by khronokernel** [comment]
So seems a bit of misworning on my part, it should be something lie this:
> Note that it requires a device named EC to function correctly

Reason for this is AppleBusPowerController with only attach to devices named EC, but for us it doesn't matter whether it's a real EC renamed or a fake one from our SSDT-EC since we're running PC hardware that already does a bunch of the work for us. We just need AppleBusPower to fix USB Power values.

I'll fix this shortly, thanks for pointing this out

**Comment by khronokernel** [comment]
Should be clarified a bit better not: https://github.com/dortania/Getting-Started-With-ACPI/commit/c552c9ede5b9b7744242a72e15029b03445f7c10

**Comment by ChasonDeshotel** [comment]
Aha, that makes sense. Thank you!
